[package]
name = "get-workspace-member"
version = "0.1.0"
edition = "2024"

[dependencies]
anthropic-ai-sdk = {path = "../../../../anthropic-ai-sdk"}
tokio = { version = "1.49.0", features = ["full"] }
tracing-subscriber = "0.3.22"
tracing = "0.1.44"
